version: "3.9"

services:
  api:
    container_name: api-demo
    image: api-demo
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - db
  db:
    image: postgres:14.7
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Panha.Com
      POSTGRES_USER: postgres
      POSTGRES_DB: api-demo
      POSTGRES_HOST: api-demo.postgres.database.azure.com
      POSTGRES_PORT: 5432



