version: '3.8'

services:
  app:
    image: api-demo:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-demo
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/api-demo-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET = 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    container_name: api-demo-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-demo-db
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped