spring:
  datasource:
    password: PpEE1TptUPIJIgYLBXpUlPse2lINXNFi
    url: jdbc:postgresql://dpg-chvfh9orddlbpl7tu0pg-a.oregon-postgres.render.com:5432/ApiDemo
    username: tengpanha
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days